WebEWSD_Collecting/Controllers/CategoryController.cs
using EWSD_Collecting.DataAccess.Data;
using EWSD_Collecting.DataAccess.Repository.IRepository;
using EWSD_Collecting.Models;
using EWSD_Collecting.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace WebEWSD_Collecting.Controllers
{
    [Authorize(Roles = SD.Role_User_QAManager + "," + SD.Role_User_Administrator)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public ActionResult Index(string Searchtext, int? page)
        {
            var pageSize = 10;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Category> items = _unitOfWork.Category.GetAll().OrderByDescending(x => x.Id);
            if (!string.IsNullOrEmpty(Searchtext))
            {
                items = items.Where(x => EWSD_Collecting.Utility.Filter.FilterChar(x.Name).Contains(EWSD_Collecting.Utility.Filter.FilterChar(Searchtext)));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            ViewBag.SearchText = Searchtext;
            return View(items);
        }

        public IActionResult Create()
        {
            return View();
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Create successfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryformDb = _db.Categories.Find(id);
            var categoryformDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            //var categoryformDbsingle = _db.Categories.SingleOrDefault(u => u.Id == id);
            if (categoryformDbFirst == null)
            {
                return NotFound();
            }
            return View(categoryformDbFirst);
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["Edited"] = "Edit successfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var objIdeaTemp = _unitOfWork.Idea.GetFirstOrDefault(u => u.CategoryId == id);
            if (objIdeaTemp == null)
            {
                var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
                if (obj != null)
                {
                    _unitOfWork.Category.Remove(obj);
                    _unitOfWork.Save();
                    TempData["Deleted"] = "Delete successfully";
                    return Json(new { success = true });
                }
                else
                {
                    return NotFound();
                }
            }
            TempData["Deleted"] = "Cannot be deleted because there are ideas link to this category.";
            return Json(new { success = false });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach (var item in items)
                    {
                        var objIdeaTemp = _unitOfWork.Idea.GetFirstOrDefault(u => u.CategoryId == Convert.ToInt32(item));
                        if (objIdeaTemp != null)
                        {
                            TempData["Deleted"] = "Cannot be deleted because there are ideas link to some categories.";
                            return Json(new { success = false });
                        }
                    }
                    foreach (var item in items)
                    {
                        var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == Convert.ToInt32(item));
                        _unitOfWork.Category.Remove(obj);
                        _unitOfWork.Save();
                        TempData["Deleted"] = "Delete successfully";
                    }
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

WebEWSD_Collecting/Controllers/StatisticController.cs
using EWSD_Collecting.DataAccess.Repository.IRepository;
using EWSD_Collecting.Models.ViewModel;
using EWSD_Collecting.Utility;
using DocumentFormat.OpenXml.Vml;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebEWSD_Collecting.Controllers
{
    [Authorize(Roles = SD.Role_User_QACoordinator + "," + SD.Role_User_QAManager + "," + SD.Role_User_Administrator)]
    public class StatisticController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public StatisticController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            StatisticVM obj = new StatisticVM();
            obj.Total_Ideas_without_comment = _unitOfWork.Idea.GetAll(u => u.Comments == 0).Count();
            obj.List_Ideas_without_comment = _unitOfWork.Idea.GetAll(u => u.Comments == 0, includeProperties: "ApplicationUser").OrderByDescending(x => x.CreateDatetime);
            obj.Total_Ideas_ANONYMOUS = _unitOfWork.Idea.GetAll(u => u.isDisplay == false).Count();
            obj.List_Ideas_ANONYMOUS = _unitOfWork.Idea.GetAll(u=>u.isDisplay == false).OrderByDescending(x => x.CreateDatetime);
            obj.Total_COMMENT_ANONYMOUS = _unitOfWork.Comment.GetAll(u => u.isDisplay == false).Count();
            obj.List_COMMENT_ANONYMOUS = _unitOfWork.Comment.GetAll(u => u.isDisplay == false, includeProperties: "Idea").OrderByDescending(x => x.CreateDatetime);
            return View(obj);
        }
        [HttpPost]
        public List<object> Percentageofideas()
        {
            List<object> data = new List<object>();
            List<string> labels = _unitOfWork.Department.GetAll().Select(i => i.Name).ToList();
            data.Add(labels);
            int totalIdeas = _unitOfWork.Idea.GetAll().Count();
            List<int> labelsint = _unitOfWork.Department.GetAll().Select(i => i.Id).ToList();
            List<int> datasets = new List<int>();
            foreach (int i in labelsint)
            {
                datasets.Add((int)Math.Round((double)(100 * _unitOfWork.Idea.GetAll(h => h.ApplicationUser.DepartmentId == i).Count()) / totalIdeas));
            }
            data.Add(datasets);
            return data;
        }
        [HttpPost]
        public List<object> Numberofideas()
        {
            List<object> data = new List<object>();
            List<string> labels = _unitOfWork.Department.GetAll().Select(i => i.Name).ToList();
            data.Add(labels);
            List<int> labelsint = _unitOfWork.Department.GetAll().Select(i => i.Id).ToList();
            List<int> datasets = new List<int>();
            foreach (int i in labelsint)
            {
                datasets.Add(_unitOfWork.Idea.GetAll(h => h.ApplicationUser.DepartmentId == i).Count());
            }
            data.Add(datasets);
            return data;
        }
        [HttpPost]
        public List<object> Numberofcontributors()
        {
            List<object> data = new List<object>();
            List<string> labels = _unitOfWork.Department.GetAll().Select(i => i.Name).ToList();
            data.Add(labels);
            List<int> labelsint = _unitOfWork.Department.GetAll().Select(i => i.Id).ToList();
            List<int> datasets = new List<int>();
            foreach (int i in labelsint)
            {
                datasets.Add(_unitOfWork.ApplicationUser.GetAll(h => h.DepartmentId == i).Count());
            }
            data.Add(datasets);
            return data;
        }
    }
}

WebEWSD_Collecting/Controllers/TopicController.cs
using EWSD_Collecting.DataAccess.Repository.IRepository;
using EWSD_Collecting.Models;
using EWSD_Collecting.Utility;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace WebEWSD_Collecting.Controllers
{
    [Authorize(Roles = SD.Role_User_QAManager + "," + SD.Role_User_Administrator + "," +SD.Role_User_QACoordinator)]
    public class TopicController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public TopicController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index(string Searchtext, int? page)
        {
            var pageSize = 10;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Topic> items = _unitOfWork.Topic.GetAll().OrderByDescending(x => x.Id);
            if (!string.IsNullOrEmpty(Searchtext))
            {
                items = items.Where(x => EWSD_Collecting.Utility.Filter.FilterChar(x.Name).Contains(EWSD_Collecting.Utility.Filter.FilterChar(Searchtext)));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            ViewBag.SearchText = Searchtext;
            return View(items);
        }
        public IActionResult Create()
        {
            return View();
        }
        //Post Ceate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Topic obj)
        {
            obj.CreateDatetime = DateTime.Now;
            if (obj.ClosureDate < DateTime.Now)
            {
                TempData["Deleted"] = "Closure Date must be after Today";
                return View(obj);
            }
            if (obj.FinalClosureDate < obj.ClosureDate)
            {
                TempData["Deleted"] = "Final Closure Date must be after Closure Date";
                return View(obj);
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Topic.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "Create successfully";
                return RedirectToAction("index");
            }
            TempData["Deleted"] = "Create Failed";
            return View(obj);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id <= 0)
            {
                return NotFound();
            }
            var topicformDb = _unitOfWork.Topic.GetFirstOrDefault(x => x.Id == id);
            //var departmentformDb = _db.Departments.Find(id);
            //var departmentformDbFirst = _db.Departments.FirstOrDefault(u=>u.Id== id);
            //var departmentformDbsingle = _db.Departments.SingleOrDefault(u => u.Id == id);
            if (topicformDb == null)
            {
                return NotFound();
            }
            return View(topicformDb);
        }
        //post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Topic obj)
        {
            if (obj.ClosureDate < obj.CreateDatetime)
            {
                TempData["Deleted"] = "Closure Date must be after Create Date";
                return View(obj);
            }
            if (obj.FinalClosureDate < obj.ClosureDate)
            {
                TempData["Deleted"] = "Final Closure Date must be after Closure Date";
                return View(obj);
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Topic.Update(obj);
                _unitOfWork.Save();
                TempData["Edited"] = "Edit successfully";
                return RedirectToAction("index");
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var objIdeaTemp = _unitOfWork.Idea.GetFirstOrDefault(u => u.TopicId == id);
            if (objIdeaTemp == null)
            {
                var obj = _unitOfWork.Topic.GetFirstOrDefault(u => u.Id == id);
                if (obj != null)
                {
                    _unitOfWork.Topic.Remove(obj);
                    _unitOfWork.Save();
                    TempData["Deleted"] = "Delete successfully";
                    return Json(new { success = true });
                }
                else
                {
                    return NotFound();
                }
            }
            TempData["Deleted"] = "Cannot be deleted because there are ideas present in this topic.";
            return Json(new { success = false });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach(var item  in items)
                    {
                        var objIdeaTemp = _unitOfWork.Idea.GetFirstOrDefault(u => u.TopicId == Convert.ToInt32(item));
                        if (objIdeaTemp != null)
                        {
                            TempData["Deleted"] = "Cannot be deleted because there are ideas present in some topic.";
                            return Json(new { success = false });
                        }
                    }
                    foreach (var item in items)
                    {
                        var obj = _unitOfWork.Topic.GetFirstOrDefault(u => u.Id == Convert.ToInt32(item));
                        _unitOfWork.Topic.Remove(obj);
                        _unitOfWork.Save();
                        TempData["Deleted"] = "Delete successfully";
                    }
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

WebEWSD_Collecting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Great Ideas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/css/Bootswatch.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/WebEWSD_Collecting.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Rye&display=swap" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/star-wars" rel="stylesheet">
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>


</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <div class="container-fluid">
                              <a class="navbar-brand" style="text-align:center;" asp-area="" asp-controller="Home" asp-action="Index">.</a>

                @if (User.IsInRole("Administrator") || User.IsInRole("QAManager") || User.IsInRole("QACoordinator") || User.IsInRole("Staff"))
                {
                                                                <div class="src">
                                                                    <form asp-controller="Idea" asp-action="Index" method="get" class="searchform">
                                                                        <i class='bx bx-search-alt'></i>
                                                                        <input type="text" name="Searchtext" placeholder="Search topic.." />
                                                                    </form>

                        </div>
                }

        </nav>
    </header>

    <div class="sidebar active">
        <div class="logo_content">
            <div class="logo">
                <div class="logo_brand">
                </div>
            </div>
            <i class='bx bx-menu' id='btn'></i>
        </div>
        <div class="row" style="margin-bottom: 100px;">

        <partial name="_LoginPartial" />
        </div>
        <ul class="sub-nav">
            <li>
                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class='bx bx-home-circle'></i>
                    <span class="link_name"> Home</span>
                </a>
            </li>
            @if (User.IsInRole("Administrator") || User.IsInRole("QAManager"))
            {
                                                                    <li>
                                                                        <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">
                                                                            <i class='bx bx-category-alt'></i>
                                                                            <span class="link_name"> Category</span>
                                                                        </a>
                                                                    </li>
            }
            @if (User.IsInRole("Administrator") || User.IsInRole("QAManager") || User.IsInRole("QACoordinator"))
            {
                                                                    <li>
                                                                        <a class="dropdown-item" asp-area="" asp-controller="Topic" asp-action="Index">
                                                                            <i class='bx bx-news'></i>
                                                                            <span class="link_name">Topic</span>
                                                                        </a>
                                                                    </li>
            }
            @if (User.IsInRole("Administrator") || User.IsInRole("QAManager") || User.IsInRole("QACoordinator"))
            {
                                                                    <li>
                                                                        <a class="dropdown-item" asp-area="" asp-controller="Statistic" asp-action="Index">
                                                                            <i class='bx bx-stats'></i>
                                                                            <span class="link_name">Statitics</span>
                                                                        </a>
                                                                    </li>
            }
            @if (User.IsInRole("Administrator") || User.IsInRole("QAManager") || User.IsInRole("QACoordinator") || User.IsInRole("Staff"))
            {
                                                                    <li>
                                                                        <a class="dropdown-item" asp-area="" asp-controller="Idea" asp-action="Index">
                                                                            <i class='bx bx-brightness'></i>
                                                                            <span class="link_name"> Ideas</span>
                                                                        </a>
                                                                    </li>
            }
            @if (User.IsInRole("Administrator"))
            {
                                                                    <li>
                                                                        <a class="dropdown-item" asp-area="" asp-controller="Department" asp-action="Index">
                                                                            <i class='bx bx-git-branch'></i>
                                                                            <span class="link_name"> Department</span>
                                                                        </a>
                                                                    </li>
            }
            @if (User.IsInRole("Administrator"))
            {
                                                                    <li>
                                                                        <a class="dropdown-item" asp-controller="Account" asp-area="" asp-action="Index">
                                                                            <i class="bi bi-person-fill-gear"></i>
                                                                            <span class="link_name">Manage Account</span>
                                                                        </a>
                                                                    </li>
            }


        </ul>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebEWSD_Collecting/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script>
            toastr.success('@TempData["Success"]')
        </script>
}
@if (TempData["Deleted"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script>
            toastr.error('@TempData["Deleted"]')
        </script>
}
@if (TempData["Edited"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script>
            toastr.warning('@TempData["Edited"]')
        </script>
}